name: Deploy to Cloud Run

on:
  push:
    branches:
      - main

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          tags: type=raw,value=latest

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

      - name: Google Auth
        id: auth
        if: env.GCP_CREDS != ''
        uses: google-github-actions/auth@v2
        env:
          GCP_CREDS: ${{ secrets.GCP_CREDENTIALS }}
        with:
          credentials_json: '${{ secrets.GCP_CREDENTIALS }}'

      - name: Set up Cloud SDK
        if: env.GCP_CREDS != ''
        uses: google-github-actions/setup-gcloud@v2
        env:
          GCP_CREDS: ${{ secrets.GCP_CREDENTIALS }}

      - name: Deploy to Cloud Run
        if: env.GCP_CREDS != ''
        env:
          GCP_CREDS: ${{ secrets.GCP_CREDENTIALS }}
        # NOTE: Be sure to set up the ENVIRONMENT VARIABLES (DATABASE_URL, REDIS_URL) directly in the GCP console for this new service
        run: |
          # Lowercase the image name for GCP
          IMAGE=$(echo "ghcr.io/${{ env.IMAGE_NAME }}:latest" | tr '[:upper:]' '[:lower:]')
          gcloud run deploy kanban-cloud \
            --image=$IMAGE \
            --region=asia-south1 \
            --allow-unauthenticated \
            --max-instances=2 \
            --min-instances=0
